# Generated by Django 3.0 on 2020-01-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_offer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopItems',
            new_name='ShopItem',
        ),
    ]
